/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas.frm;

import conexao.conexaobanco;
import javax.swing.JOptionPane;
import java.text.DateFormat;
import java.sql.Date;
import java.sql.*;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
        

/**
 *
 * @author Dailiane
 */
public class inicio extends javax.swing.JFrame {
    Connection conexao = null;
    
    /**
     * Creates new form inicio
     */
    public inicio() {
        initComponents();
        conexao = conexaobanco.conector();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenu2 = new javax.swing.JMenu();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        inicio = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        menu_cadastro = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        menu_certidao = new javax.swing.JMenu();
        relatorio = new javax.swing.JMenuItem();
        menu_configuracao = new javax.swing.JMenu();
        cdusuario = new javax.swing.JMenuItem();
        busuario = new javax.swing.JMenuItem();
        menu_ajuda = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jMenu2.setText("jMenu2");

        jMenuItem1.setText("jMenuItem1");

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setTitle("SIGP");
        jInternalFrame1.setVisible(true);

        inicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/wallpaperbetter.jpg"))); // NOI18N
        inicio.setText("jLabel1");
        inicio.setMaximumSize(new java.awt.Dimension(1700, 800));

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/imagens/icones/Inicio.png"))); // NOI18N
        jMenu7.setText("Sistema");
        jMenu7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/imagens/icones/About.png"))); // NOI18N
        jMenuItem8.setText("Sobre");
        jMenuItem8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem8);

        jMenuBar2.add(jMenu7);

        menu_cadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/imagens/icones/Actions-list-add-user-icon.png"))); // NOI18N
        menu_cadastro.setText("Cadastro");
        menu_cadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu_cadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_cadastroActionPerformed(evt);
            }
        });

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/imagens/icones/Actions-contact-new-icon.png"))); // NOI18N
        jMenu3.setText("Cadastro de Batismo");

        jMenuItem3.setText("NºAntigo");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        menu_cadastro.add(jMenu3);

        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/imagens/icones/Find.png"))); // NOI18N
        jMenuItem7.setText("Buscar");
        jMenuItem7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        menu_cadastro.add(jMenuItem7);

        jMenuBar2.add(menu_cadastro);

        menu_certidao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/imagens/icones/List.png"))); // NOI18N
        menu_certidao.setText("Relatório");
        menu_certidao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        relatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/imagens/icones/print.png"))); // NOI18N
        relatorio.setText("Emitir Relatório");
        relatorio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        relatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relatorioActionPerformed(evt);
            }
        });
        menu_certidao.add(relatorio);

        jMenuBar2.add(menu_certidao);

        menu_configuracao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/imagens/icones/configurações.png"))); // NOI18N
        menu_configuracao.setText("Configurações");
        menu_configuracao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu_configuracao.setEnabled(false);

        cdusuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/imagens/icones/restringir usuario 32x32.png"))); // NOI18N
        cdusuario.setText("Cadastrar Usuários ");
        cdusuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cdusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdusuarioActionPerformed(evt);
            }
        });
        menu_configuracao.add(cdusuario);

        busuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/imagens/icones/Find.png"))); // NOI18N
        busuario.setText("Buscar Usuarios");
        busuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        busuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busuarioActionPerformed(evt);
            }
        });
        menu_configuracao.add(busuario);

        jMenuBar2.add(menu_configuracao);

        menu_ajuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/imagens/icones/ajuda.png"))); // NOI18N
        menu_ajuda.setText("Ajuda");
        menu_ajuda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/imagens/icones/Exit.png"))); // NOI18N
        jMenuItem10.setText("Sair");
        jMenuItem10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        menu_ajuda.add(jMenuItem10);

        jMenuBar2.add(menu_ajuda);

        jInternalFrame1.setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addComponent(inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 1335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addComponent(inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 347, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cdusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdusuarioActionPerformed
         CadastroUsuario cadastroU = new CadastroUsuario();
         inicio.add(cadastroU);
         cadastroU.toFront();
        cadastroU.setVisible(true);
    }//GEN-LAST:event_cdusuarioActionPerformed

    private void busuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busuarioActionPerformed
        BuscaUsuario busca = new BuscaUsuario();
        inicio.add(busca);
        busca.toFront ();
        busca.setVisible (true);
    }//GEN-LAST:event_busuarioActionPerformed

    private void relatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relatorioActionPerformed
        // GERANDO RELATORIO DE CADASTROS DE BATISMO
        Relatorio relatoriob = new Relatorio();
        inicio.add(relatoriob);
        relatoriob.toFront();
        relatoriob.setVisible(true);
       
    }//GEN-LAST:event_relatorioActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // sair sistema
        int sair = JOptionPane.showConfirmDialog(null, "Deseja sair do Sistema?","Atenção",JOptionPane.YES_NO_OPTION);
        if (sair == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void menu_cadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_cadastroActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_menu_cadastroActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        BuscaBatismo busc = new BuscaBatismo();
        inicio.add(busc);
        busc.toFront();
        busc.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        //CHAMANDO A TELA DE CADASTROBATISMO PARA O INICIO
        CadastroBatismo batismo = new CadastroBatismo();
        inicio.add(batismo);
        batismo.toFront();
        batismo.setVisible(true);

    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem busuario;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JMenuItem cdusuario;
    private javax.swing.JLabel inicio;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JMenu menu_ajuda;
    private javax.swing.JMenu menu_cadastro;
    private javax.swing.JMenu menu_certidao;
    public static javax.swing.JMenu menu_configuracao;
    private javax.swing.JMenuItem relatorio;
    // End of variables declaration//GEN-END:variables
}
